name: digikala_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  percent_indicator: ^4.2.3
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/abzar/
    - assets/images/app/
    - assets/images/back/
    - assets/images/baners/
    - assets/images/categories/
    - assets/images/gift/
    - assets/images/gift_super/
    - assets/images/mobile/
    - assets/images/mobile_cover/
    - assets/images/product/
    - assets/images/svg/
    - assets/images/icons/

  fonts:
    - family: kalameh
      fonts:
        - asset: assets/fonts/KalamehFaNum.ttf
    - family: morabba
      fonts:
        - asset: assets/fonts/morabba.ttf
    - family: yekan
      fonts:
        - asset: assets/fonts/IRANYekanMobileRegular.ttf
        - asset: assets/fonts/IRANYekanMobileBold.ttf
          weight: 700
